version: "3.6"


services:
  # Web service layer
  nginx:
    image: nginx:1.17
    volumes:
      - ./app:/var/www/html
      - ./moodledata:/var/moodledata      
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
      - ./nginx/sites:/etc/nginx/sites-available
    ports:
      - "8080:80"
    depends_on:
      - php
   
  php:
    build:
      context: ./php
    volumes:
      - ./php/php7.2.ini:/usr/local/etc/php/php.ini
      - ./app:/var/www/html
      - ./moodledata:/var/moodledata

    ports:
      - "9000:9000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
   

  postgres:
    image: postgres:9.6
    volumes:
      - ./postgres/.store/data:/var/lib/postgresql/data      
    ports:
      #altere caso ocorra conflitos
      - "5433:5432"
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
